version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: 1
    BUILDKIT_PROGRESS: plain
    NODE_ENV: production
    NEXT_TELEMETRY_DISABLED: 1

phases:
  pre_build:
    commands:
      - echo "Starting Frontend ECS build on $(date)"
      - echo "Build Environment Info:"
      - echo "  - AWS Region $AWS_DEFAULT_REGION"
      - echo "  - Account ID $AWS_ACCOUNT_ID"
      - echo "  - Build ID $CODEBUILD_BUILD_ID"
      - echo "  - Source Version $CODEBUILD_SOURCE_VERSION"
      - echo "  - Node Version $(node --version)"
      - echo "  - NPM Version $(npm --version)"
      - echo "  - Docker Version $(docker --version)"

      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

      - echo "Pre-build completed successfully"

  build:
    commands:
      - echo "Building Docker image..."
      - IMAGE_TAG=${CODEBUILD_BUILD_NUMBER:-latest}
      - ECR_REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME
      - echo "Using CONTAINER_NAME from environment = $CONTAINER_NAME"
      
      - echo "Docker Build Info:"
      - echo "  - Image Tag $IMAGE_TAG"
      - echo "  - ECR Repository URI $ECR_REPO_URI"
      - echo "  - Container Name $CONTAINER_NAME"
      
      - echo "Building Docker image for Frontend..."
      - |
        cat > Dockerfile << 'EOF'
        # Multi-stage build for Next.js frontend
        FROM node:20-alpine AS base
        
        # Install dependencies only when needed
        FROM base AS deps
        RUN apk add --no-cache libc6-compat
        WORKDIR /app
        
        # Copy package files
        COPY package*.json ./
        RUN npm ci --frozen-lockfile --ignore-scripts
        
        # Rebuild the source code only when needed
        FROM base AS builder
        WORKDIR /app
        COPY --from=deps /app/node_modules ./node_modules
        COPY . .
        
        # Disable Next.js telemetry during build
        ENV NEXT_TELEMETRY_DISABLED 1
        ARG NEXT_PUBLIC_WEB_URL
        ARG NEXT_PUBLIC_IS_LOCALHOST
        ARG NEXT_PUBLIC_AWS_USER_POOL_ID
        ARG NEXT_PUBLIC_AWS_USER_POOL_CLIENT_ID
        ARG NEXT_PUBLIC_API_GRAPHQL_URL
        
        ENV NEXT_PUBLIC_WEB_URL $NEXT_PUBLIC_WEB_URL
        ENV NEXT_PUBLIC_IS_LOCALHOST $NEXT_PUBLIC_IS_LOCALHOST
        ENV NEXT_PUBLIC_AWS_USER_POOL_ID $NEXT_PUBLIC_AWS_USER_POOL_ID
        ENV NEXT_PUBLIC_AWS_USER_POOL_CLIENT_ID $NEXT_PUBLIC_AWS_USER_POOL_CLIENT_ID
        ENV NEXT_PUBLIC_API_GRAPHQL_URL $NEXT_PUBLIC_API_GRAPHQL_URL
        
        # Generate GraphQL types before build
        RUN echo "Generating GraphQL types..." && \
            (npm run codegen || npm run generate || npm run graphql:generate || \
             npm run gql:generate || npx graphql-codegen || \
             echo "GraphQL codegen command not found - skipping")
        
        RUN npm run build -- --no-lint
        
        # Production image, copy all the files and run next
        FROM base AS runner
        WORKDIR /app
        
        ENV NODE_ENV production
        ENV NEXT_TELEMETRY_DISABLED 1
        
        # Install curl for health check before switching users
        RUN apk add --no-cache curl
        
        RUN addgroup --system --gid 1001 nodejs
        RUN adduser --system --uid 1001 nextjs
        
        # Copy the necessary files
        COPY --from=builder /app/public ./public
        
        # Set the correct permission for prerender cache
        RUN mkdir .next
        RUN chown nextjs:nodejs .next
        
        # Copy Next.js build output and dependencies
        COPY --from=builder /app/package*.json ./
        COPY --from=builder /app/node_modules ./node_modules
        COPY --from=builder /app/.next ./.next
        
        USER nextjs
        
        EXPOSE 3000
        ENV PORT 3000
        
        # Add health check
        HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
          CMD curl -f http://localhost:3000/fe/api/health || exit 1
        
        CMD ["npm", "start"]
        EOF

      
      - echo "Building with Next.js environment variables..."
      - echo "  - NEXT_PUBLIC_WEB_URL=$NEXT_PUBLIC_WEB_URL"
      - echo "  - NEXT_PUBLIC_IS_LOCALHOST=$NEXT_PUBLIC_IS_LOCALHOST"  
      - echo "  - NEXT_PUBLIC_AWS_USER_POOL_ID=$NEXT_PUBLIC_AWS_USER_POOL_ID"
      - echo "  - NEXT_PUBLIC_AWS_USER_POOL_CLIENT_ID=$NEXT_PUBLIC_AWS_USER_POOL_CLIENT_ID"
      - echo "  - NEXT_PUBLIC_API_GRAPHQL_URL=$NEXT_PUBLIC_API_GRAPHQL_URL"

      
      
      - |
        docker build \
          --build-arg NEXT_PUBLIC_WEB_URL="$NEXT_PUBLIC_WEB_URL" \
          --build-arg NEXT_PUBLIC_IS_LOCALHOST="$NEXT_PUBLIC_IS_LOCALHOST" \
          --build-arg NEXT_PUBLIC_AWS_USER_POOL_ID="$NEXT_PUBLIC_AWS_USER_POOL_ID" \
          --build-arg NEXT_PUBLIC_AWS_USER_POOL_CLIENT_ID="$NEXT_PUBLIC_AWS_USER_POOL_CLIENT_ID" \
          --build-arg NEXT_PUBLIC_API_GRAPHQL_URL="$NEXT_PUBLIC_API_GRAPHQL_URL" \
          -t $ECR_REPO_URI:$IMAGE_TAG .
      - docker tag $ECR_REPO_URI:$IMAGE_TAG $ECR_REPO_URI:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - docker push $ECR_REPO_URI:latest
      - echo "Image pushed successfully"
      
      - echo "Generating imagedefinitions.json for ECS deployment..."
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$ECR_REPO_URI:$IMAGE_TAG" > imagedefinitions.json
      - echo "Generated imagedefinitions.json:"
      - cat imagedefinitions.json
      - echo "Build completed successfully on $(date)"

artifacts:
  files:
    - imagedefinitions.json
  name: frontend-fe-build-artifacts-$(date +%Y-%m-%d-%H-%M-%S)

cache:
  paths:
    - node_modules/**/*
    - ~/.npm/**/*

reports:
  jest_reports:
    files:
      - test-results/jest/junit.xml
    base-directory: .
    file-format: JUNITXML
