version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "ðŸ”§ Installing dependencies..."
      - echo "Installing required tools"
      - apt-get update -qq && apt-get install -y jq

  pre_build:
    commands:
      - echo "ðŸ” Pre-build phase started on $(date)"
      - echo "Environment $STAGE"
      - echo "ECR Repository $ECR_REPO_URI"
      - echo "Container Name $CONTAINER_NAME"
      - echo "Image Tag $IMAGE_TAG"
      - echo "ðŸ³ Setting up Docker environment..."

      - mkdir -p /var/run
      - rm -f /var/run/docker.sock
      - echo "ðŸ³ Starting Docker daemon..."
      - nohup /usr/local/bin/dockerd --host=tcp://127.0.0.1:2375
        --storage-driver=overlay2 --insecure-registry $ECR_REPO_URI >
        /tmp/dockerd.log 2>&1 &
      - export DOCKER_HOST=tcp://127.0.0.1:2375
      - echo "â³ Waiting for Docker daemon to be ready..."
      - timeout 30 sh -c "until docker info > /dev/null 2>&1; do echo 'Waiting
        for Docker...'; sleep 2; done"
      - echo "âœ… Docker daemon is ready"
      - docker info

      - echo "ðŸ”‘ Authenticating to ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login
        --username AWS --password-stdin $ECR_REPO_URI

      - echo "ðŸ“‹ Setting up environment for Spring Boot build..."
      - echo "Java version:"
      - java -version
      - echo "Gradle version:"
      - ./gradlew --version

  build:
    commands:
      - echo "ðŸ— Building Spring Boot application..."
      - echo "Build started on $(date)"

      - echo "ðŸ§ª Running tests..."
      - ./gradlew clean test --info

      - echo "ðŸ“¦ Building JAR file..."
      - ./gradlew build -x test --info
      - echo "âœ… JAR build completed"

      - echo "ðŸ“ Listing build artifacts..."
      - ls -la build/libs/

      - echo "ï¿½ Building Docker image using existing Dockerfile..."
      - docker build -t $ECR_REPO_NAME:$IMAGE_TAG .
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $ECR_REPO_URI:$IMAGE_TAG
      - echo "âœ… Docker image built successfully"

  post_build:
    commands:
      - echo "ðŸ“¤ Post-build phase started..."
      - echo "ðŸš€ Pushing Docker image to ECR..."
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - echo "âœ… Docker image pushed successfully"
      - echo "ðŸ“ Generating imagedefinitions.json for ECS deployment..."
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME"
        "$ECR_REPO_URI:$IMAGE_TAG" > imagedefinitions.json
      - echo "Generated imagedefinitions.json:"
      - cat imagedefinitions.json
      - echo "ðŸŽ‰ Build completed successfully on $(date)"

artifacts:
  files:
    - imagedefinitions.json
  name: backend-build-artifacts-$(date +%Y-%m-%d-%H-%M-%S)

cache:
  paths:
    - /root/.gradle/caches/**/*
    - /root/.gradle/wrapper/**/*

reports:
  junit:
    files:
      - build/test-results/test/TEST-*.xml
    base-directory: .
    file-format: JUNITXML
Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AliasAttributes:
        - email
        - preferred_username
      UserPoolName: !Sub ${AWS::StackName}-UserPool
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.health
Metadata:
  AWS::Composer::Groups:
    Group:
      Label: Group
      Members:
        - UserPool