version: 0.0
os: linux
files:
  - source: /
    destination: /opt/auditstage/app
    overwrite: true
permissions:
  - object: /opt/auditstage/app
    pattern: "**"
    owner: auditstage
    group: auditstage
    mode: 755
  - object: /opt/auditstage/app/scripts
    pattern: "**"
    owner: root
    group: root
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/stop_application.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/setup_permissions.sh  
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: root
